<a href="https://colab.research.google.com/github/ajeeshnadh/DSA_Projects/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
    arr = np.arange(10, 50)
    reshaped = arr.reshape(4, 10)
    last_column = reshaped[:, -1]
    print("Reshaped array:\n", reshaped)
    print("Last column:\n", last_column)


Reshaped array:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Last column:
 [19 29 39 49]


In [ ]:

    mat1 = np.full((3, 3), 5)
    mat2 = np.arange(1, 10).reshape(3, 3)
    added = mat1 + mat2
    multiplied = mat1 * mat2
    transposed = multiplied.T
    print("Matrix 1:\n", mat1)
    print("Matrix 2:\n", mat2)
    print("Added:\n", added)
    print("Multiplied (element-wise):\n", multiplied)
    print("Transposed result:\n", transposed)


Matrix 1:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Matrix 2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Added:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Multiplied (element-wise):
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transposed result:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [ ]:

    arr = np.random.randint(10, 101, 15)
    print("Original array:", arr)
    replaced = np.where(arr > 50, -1, arr)
    count_replaced = np.sum(arr > 50)
    print("Modified array:", replaced)
    print("Count of replaced values:", count_replaced)


Original array: [ 73  93  94  97  44  81  54  89  11  85  50 100  33  98  35]
Modified array: [-1 -1 -1 -1 44 -1 -1 -1 11 -1 50 -1 33 -1 35]
Count of replaced values: 10


In [ ]:
 arr = np.random.rand(5, 4)
    print("Original array:\n", arr)
    row_sums = np.sum(arr, axis=1)
    max_row_index = np.argmax(row_sums)
    print("Row with max sum:", max_row_index)
    normalized = arr / arr.sum(axis=1, keepdims=True)
    print("Normalized array:\n", normalized)


Original array:
 [[0.2454219  0.8735326  0.72333667 0.97557712]
 [0.56564672 0.44837961 0.97883902 0.79645603]
 [0.04767225 0.84893003 0.52191601 0.67337162]
 [0.27083719 0.61607316 0.36036294 0.25789689]
 [0.14166102 0.91390505 0.39748192 0.27778705]]
Row with max sum: 0
Normalized array:
 [[0.08709488 0.30999767 0.25669641 0.34621104]
 [0.20279008 0.16074864 0.35092371 0.28553756]
 [0.02278908 0.40581965 0.24949497 0.3218963 ]
 [0.17993792 0.40930465 0.23941674 0.17134068]
 [0.08184548 0.52801395 0.22964749 0.16049308]]


In [ ]:
    arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
    unique_elements = np.unique(arr)
    duplicates = np.array([x for x in unique_elements if np.count_nonzero(arr == x) > 1])
    print("Unique elements:", unique_elements)
    print("Duplicates:", duplicates)


Unique elements: [1 3 5 7 9]
Duplicates: [1 3 5]


In [ ]:
    arr = np.arange(1, 37).reshape(6, 6)
    submatrix = arr[1:5, 1:5]
    even_numbers = submatrix[submatrix % 2 == 0]
    print("Original array:\n", arr)
    print("4x4 Middle submatrix:\n", submatrix)
    print("Even numbers in submatrix:", even_numbers)


Original array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
4x4 Middle submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even numbers in submatrix: [ 8 10 14 16 20 22 26 28]


In [ ]:

    arr = np.arange(12).reshape(3, 4)
    reshaped_2_6 = arr.reshape(2, 6)
    flattened = reshaped_2_6.flatten()
    reshaped_4_3 = flattened.reshape(4, 3)
    print("Original array:\n", arr)
    print("Reshaped to 2x6:\n", reshaped_2_6)
    print("Flattened array:", flattened)
    print("Reshaped to 4x3:\n", reshaped_4_3)


Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 4x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:

    a = np.array([[1, 2], [3, 4]])
    a = np.append(a, [[5, 6]], axis=0)
    a = np.insert(a, a.shape[1], [7, 8, 9], axis=1)
    print("Array after appending row and column:\n", a)


Array after appending row and column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:

    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    c = np.array([7, 8, 9])
    joined = np.concatenate((a, b, c))
    reshaped = joined.reshape(3, 3)
    diagonal = np.diag(reshaped)
    print("Joined array:", joined)
    print("Reshaped (3x3):\n", reshaped)
    print("Diagonal elements:", diagonal)


Joined array: [1 2 3 4 5 6 7 8 9]
Reshaped (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal elements: [1 5 9]


In [ ]:

    arr = np.arange(1, 21)
    divisible = arr[(arr % 3 == 0) | (arr % 5 == 0)]
    count = divisible.size
    print("Divisible by 3 or 5:", divisible)
    print("Count:", count)

Divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]
Count: 9
